version: '3'
services:
  svg-nest-app:
    image: vovochkastelmashchuk/svg-nest-web-app:latest
    ports:
      - "5001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge